# Generated by Django 2.2.5 on 2019-09-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='image_url',
        ),
    ]
